name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync-to-gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3

      - name: Push to GitLab mirror
        run: |
          git config --global user.name "${{ secrets.GITLAB_USERNAME }}"
          git config --global user.email "${{ secrets.GITLAB_USERNAME }}@stud.ntnu.no"

          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@git.gvk.idi.ntnu.no/course/prog2005/prog2005-2025-workspace/nahomba/assignment1.git

          git push --force gitlab HEAD:main
