name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror-to-gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full Git history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.GITLAB_USERNAME }}"
          git config --global user.email "${{ secrets.GITLAB_USERNAME }}@stud.ntnu.no"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@git.gvk.idi.ntnu.no/course/prog2005/prog2005-2025-workspace/nahomba/assignment-2.git

      - name: Push to GitLab
        run: |
          git push --force gitlab HEAD:main
